apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        tier: front-end
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      tier: front-end
      