apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    tier: front-end
spec:
## type can be NodePort/ClusterIP/LoadBalancer
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    tier: front-end